# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - event-dsh-demo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Fix permissions and build
        run: |
          # Fix permissions for node_modules/.bin
          chmod +x node_modules/.bin/*
          # Build the frontend
          npm run build

      - name: Install production dependencies only
        run: |
          # Remove dev dependencies and reinstall only production deps
          rm -rf node_modules
          npm ci --only=production

      - name: Create deployment package
        run: |
          # Create a clean deployment package
          mkdir -p deploy-package
          
          # Copy essential files
          cp package*.json deploy-package/
          cp -r backend deploy-package/
          cp -r dist deploy-package/
          cp -r node_modules deploy-package/
          
          # Copy any other necessary files
          [ -f .env ] && cp .env deploy-package/ || true

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy-package

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2C56BB6B558348169B4FEC3066243423 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0D080E0485924CBEB5134C77306DE225 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D8B124E953D94AC088D69EAD5678ADAC }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'event-dsh-demo'
          slot-name: 'Production'
          package: .